###
GET http://127.0.0.1:3003/api/pelicula
Authorization: Basic QWRtaW5TaXN0ZW1hOk1pUGFzc1NlZ3VyYTEyMw==

###
GET http://127.0.0.1:3003/api/pelicula/3
Authorization: Basic QWRtaW5TaXN0ZW1hOk1pUGFzc1NlZ3VyYTEyMw==

###
POST http://127.0.0.1:3003/api/pelicula
Authorization: Basic QWRtaW5TaXN0ZW1hOk1pUGFzc1NlZ3VyYTEyMw==
Content-Type: application/json

{
  "title": "Otra pelicula que agrego",
  "author": "El autor de esta pelicula",
  "puntaje": 97.3,
  "publishedDate": "1444-06-05",
  "availableCopies": 17
}

###
PUT http://127.0.0.1:3003/api/pelicula/3
Authorization: Basic QWRtaW5TaXN0ZW1hOk1pUGFzc1NlZ3VyYTEyMw==
Content-Type: application/json

{
  "title": "Peli actualizada",
  "author": "Nuevo autor",
  "puntaje": 98.1,
  "publishedDate": "2024-06-05",
  "availableCopies": 8
}

###
DELETE http://127.0.0.1:3003/api/pelicula/6
Authorization: Basic QWRtaW5TaXN0ZW1hOk1pUGFzc1NlZ3VyYTEyMw==

###
GET http://127.0.0.1:3003/api/pelicula/estadisticas
Authorization: Basic QWRtaW5TaXN0ZW1hOk1pUGFzc1NlZ3VyYTEyMw==

###
GET http://127.0.0.1:3003/api/pelicula/exportar
Authorization: Basic QWRtaW5TaXN0ZW1hOk1pUGFzc1NlZ3VyYTEyMw==

###
# ❌ Prueba NO FELIZ - Exportar sin películas
DELETE http://127.0.0.1:3003/api/pelicula/all
Authorization: Basic QWRtaW5TaXN0ZW1hOk1pUGFzc1NlZ3VyYTEyMw==

###
GET http://127.0.0.1:3003/api/pelicula/exportar
Authorization: Basic QWRtaW5TaXN0ZW1hOk1pUGFzc1NlZ3VyYTEyMw==
